//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.3649
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartExcel.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/Newtera/WebService/MetaDataWebService.asmx")]
        public string SmartExcel_MetaDataWebService_MetaDataService {
            get {
                return ((string)(this["SmartExcel_MetaDataWebService_MetaDataService"]));
            }
            set {
                this["SmartExcel_MetaDataWebService_MetaDataService"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/Newtera/WebService/AdminWebService.asmx")]
        public string SmartExcel_AdminWebService_AdminService {
            get {
                return ((string)(this["SmartExcel_AdminWebService_AdminService"]));
            }
            set {
                this["SmartExcel_AdminWebService_AdminService"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/Newtera/WebService/CMDataWebService.asmx")]
        public string SmartExcel_CMDataWebService_CMDataService {
            get {
                return ((string)(this["SmartExcel_CMDataWebService_CMDataService"]));
            }
            set {
                this["SmartExcel_CMDataWebService_CMDataService"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/Newtera/WebService/UserInfoWebService.asmx")]
        public string SmartExcel_UserInfoWebService_UserInfoService {
            get {
                return ((string)(this["SmartExcel_UserInfoWebService_UserInfoService"]));
            }
            set {
                this["SmartExcel_UserInfoWebService_UserInfoService"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/Newtera/WebService/WorkflowModelWebService.asmx")]
        public string SmartExcel_WorkflowModelWebService_WorkflowModelService {
            get {
                return ((string)(this["SmartExcel_WorkflowModelWebService_WorkflowModelService"]));
            }
            set {
                this["SmartExcel_WorkflowModelWebService_WorkflowModelService"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/Newtera/WebService/OLAPWebService.asmx")]
        public string SmartExcel_OLAPWebService_OLAPService {
            get {
                return ((string)(this["SmartExcel_OLAPWebService_OLAPService"]));
            }
            set {
                this["SmartExcel_OLAPWebService_OLAPService"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/Newtera/WebService/AttachmentWebService.asmx")]
        public string SmartExcel_AttachmentWebService_AttachmentService {
            get {
                return ((string)(this["SmartExcel_AttachmentWebService_AttachmentService"]));
            }
            set {
                this["SmartExcel_AttachmentWebService_AttachmentService"] = value;
            }
        }
    }
}
