/*
* @(#)SQLAction.cs
*
* Copyright (c) 2005 Newtera, Inc. All rights reserved.
*
*/
namespace Newtera.Server.Engine.Sqlbuilder
{
	using System;

	using Newtera.Common.MetaData.Schema;
	using Newtera.Server.Engine.Sqlbuilder.Sql;

	/// <summary>
	/// The SQLAction is a class that provides information about how to execute
	/// an SQL generated by the SQLBuilder.
	/// </summary>
	/// <version>  	1.0.1 05 Apr 2005 </version>
	/// <author> Yong Zhang</author>
	public class SQLAction
	{
		/* instance variables */
		SQLStatement _statement;
		SQLActionType _actionType;
		string _data;
		string _tableName;
		string _columnName;
		string _objId;
        string _sqlTemplate;
        string _executableSQL;
        string _ownerClassName;
        string _attributeName;
		
		/// <summary>
		/// Initiating a SQLAction object.
		/// </summary>
		public SQLAction()
		{
			_actionType = SQLActionType.Select;
			_data = null;
			_tableName = null;
			_columnName = null;
			_objId = null;
            _ownerClassName = null;
            _attributeName = null;
            _sqlTemplate = null;
            _executableSQL = null;
		}

		/// <summary>
		/// Gets or sets SQLActionType value
		/// </summary>
		/// <value> One of the SQLActionType enum</value>
		public SQLActionType Type
		{
			get
			{
				return _actionType;
			}
			set
			{
				_actionType = value;
			}
		}

		/// <summary>
		/// Gets or sets SQLStatement for the action.
		/// </summary>
		/// <value>An SQLStatement instance.</value>
		public SQLStatement Statement
		{
			get
			{
				return _statement;
			}
			set
			{
				_statement = value;
			}
		}

        /// <summary>
        /// Gets or sets name of class that owns the action.
        /// </summary>
        /// <value>The owner class name.</value>
        public string OwnerClassName
        {
            get
            {
                return _ownerClassName;
            }
            set
            {
                _ownerClassName = value;
            }
        }

        /// <summary>
        /// Gets or sets name of attribute that owns the action, valid when action type is WriteClob
        /// </summary>
        /// <value>The owner attribute name.</value>
        public string AttributeName
        {
            get
            {
                return _attributeName;
            }
            set
            {
                _attributeName = value;
            }
        }

        /// <summary>
        /// Gets or sets sql template which contains variables.
        /// </summary>
        /// <value>A SQL template.</value>
        public string SQLTemplate
        {
            get
            {
                return _sqlTemplate;
            }
            set
            {
                _sqlTemplate = value;
            }
        }

        /// <summary>
        /// Gets or sets an executable sql statement.
        /// </summary>
        /// <value>A SQL string.</value>
        public string ExecutableSQL
        {
            get
            {
                return _executableSQL;
            }
            set
            {
                _executableSQL = value;
            }
        }

		/// <summary>
		/// Gets or sets clob data, used by ClobWrite action
		/// </summary>
		/// <value>A string represents clob data.</value>
		public string Data
		{
			get
			{
				return _data;
			}
			set
			{
				_data = value;
			}
		}

		/// <summary>
		/// Gets or sets table name that contains a clob column. Used by ClobWrite action
		/// </summary>
		/// <value>A string represents a database Table name.</value>
		public string TableName
		{
			get
			{
				return _tableName;
			}
			set
			{
				_tableName = value;
			}
		}

		/// <summary>
		/// Gets or sets name of a clob column. Used by ClobWrite action
		/// </summary>
		/// <value>A string represents a database column name.</value>
		public string ColumnName
		{
			get
			{
				return _columnName;
			}
			set
			{
				_columnName = value;
			}
		}

		/// <summary>
		/// Gets or sets obj_id of an database instance. Used by ClobWrite action
		/// </summary>
		/// <value>A string represents an obj_id.</value>
		public string ObjId
		{
			get
			{
				return _objId;
			}
			set
			{
				_objId = value;
			}
		}
	}

	/// <summary>
	/// Specify type of SQL action
	/// </summary>
	public enum SQLActionType
	{
        /// <summary>
        /// Invalid
        /// </summary>
        Invalid,
		/// <summary>
		/// Select SQL action
		/// </summary>
		Select,
		/// <summary>
		/// Insert SQL action
		/// </summary>
		Insert,
		/// <summary>
		/// Update SQL action
		/// </summary>
		Update,
		/// <summary>
		/// Write to a clob action
		/// </summary>
		WriteClob
	}
}