/*
* @(#)ITextParser.cs
*
* Copyright (c) 2005 Newtera, Inc. All rights reserved.
*
*/
namespace Newtera.ParserGen.ParseTree
{
	using System;
	using System.Data;
	using System.Xml;

	/// <summary>
	/// Represents a common interface for all text parsers generated by VisualParse tool.
	/// </summary>
	/// <version> 1.0.0 28 Nov 2005</version>
	/// <author> Yong Zhang </author>
	public interface ITextParser
	{
		/// <summary>
		/// Gets the root of parse tree generated by a parser.
		/// </summary>
		/// <returns>The root of the parse tree.</returns>
		IParseTreeNode ParseTreeRoot {get;}
	}
}