//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Newtera.MLStudio.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Newtera.MLStudio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Workflow aborted 的本地化字符串。
        /// </summary>
        public static string AbortedInDebugStatus {
            get {
                return ResourceManager.GetString("AbortedInDebugStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workflow aborted 的本地化字符串。
        /// </summary>
        public static string AbortedStatus {
            get {
                return ResourceManager.GetString("AbortedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workflow aborting ... 的本地化字符串。
        /// </summary>
        public static string AbortingInDebugStatus {
            get {
                return ResourceManager.GetString("AbortingInDebugStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workflow aborting ... 的本地化字符串。
        /// </summary>
        public static string AbortingServiceHostStatus {
            get {
                return ResourceManager.GetString("AbortingServiceHostStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workflow aborting ... 的本地化字符串。
        /// </summary>
        public static string AbortingStatus {
            get {
                return ResourceManager.GetString("AbortingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workflow Studio
        ///Copyright (c) Microsoft Corporation. All rights reserved.
        ///Version {0} 的本地化字符串。
        /// </summary>
        public static string AboutDialogMessage {
            get {
                return ResourceManager.GetString("AboutDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string AboutDialogTitle {
            get {
                return ResourceManager.GetString("AboutDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workflow service host closed 的本地化字符串。
        /// </summary>
        public static string ClosedServiceHostInDebugStatus {
            get {
                return ResourceManager.GetString("ClosedServiceHostInDebugStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workflow service host closed 的本地化字符串。
        /// </summary>
        public static string ClosedServiceHostStatus {
            get {
                return ResourceManager.GetString("ClosedServiceHostStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collection 的本地化字符串。
        /// </summary>
        public static string CollectionCategoryToToolbox {
            get {
                return ResourceManager.GetString("CollectionCategoryToToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workflow completed with completion state {0} 的本地化字符串。
        /// </summary>
        public static string CompletedInDebugStatus {
            get {
                return ResourceManager.GetString("CompletedInDebugStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workflow completed with completion state {0} 的本地化字符串。
        /// </summary>
        public static string CompletedStatus {
            get {
                return ResourceManager.GetString("CompletedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This workflow is running. Do you wish to exit? 的本地化字符串。
        /// </summary>
        public static string ConfirmCloseWhenRunningWorkflowDialogMessage {
            get {
                return ResourceManager.GetString("ConfirmCloseWhenRunningWorkflowDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string ConfirmCloseWhenRunningWorkflowDialogTitle {
            get {
                return ResourceManager.GetString("ConfirmCloseWhenRunningWorkflowDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are one or more running workflows. Do you wish to close? 的本地化字符串。
        /// </summary>
        public static string ConfirmCloseWhenRunningWorkflowsDialogMessage {
            get {
                return ResourceManager.GetString("ConfirmCloseWhenRunningWorkflowsDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string ConfirmCloseWhenRunningWorkflowsDialogTitle {
            get {
                return ResourceManager.GetString("ConfirmCloseWhenRunningWorkflowsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save changes to {0} 的本地化字符串。
        /// </summary>
        public static string ConfirmSaveDialogMessage {
            get {
                return ResourceManager.GetString("ConfirmSaveDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Changes 的本地化字符串。
        /// </summary>
        public static string ConfirmSaveDialogTitle {
            get {
                return ResourceManager.GetString("ConfirmSaveDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Control Flow 的本地化字符串。
        /// </summary>
        public static string ControlFlowCategoryToToolbox {
            get {
                return ResourceManager.GetString("ControlFlowCategoryToToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Debugging workflow ... 的本地化字符串。
        /// </summary>
        public static string DebuggingStatus {
            get {
                return ResourceManager.GetString("DebuggingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Debug 的本地化字符串。
        /// </summary>
        public static string DebugMenu {
            get {
                return ResourceManager.GetString("DebugMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Abort 的本地化字符串。
        /// </summary>
        public static string DebugMenuAbort {
            get {
                return ResourceManager.GetString("DebugMenuAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Debugging 的本地化字符串。
        /// </summary>
        public static string DebugMenuStartDebugging {
            get {
                return ResourceManager.GetString("DebugMenuStartDebugging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;F5&apos; 的本地化字符串。
        /// </summary>
        public static string DebugMenuStartDebuggingCommandKey {
            get {
                return ResourceManager.GetString("DebugMenuStartDebuggingCommandKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string DebugMenuStartDebuggingCommandModifier {
            get {
                return ResourceManager.GetString("DebugMenuStartDebuggingCommandModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Without Debugging 的本地化字符串。
        /// </summary>
        public static string DebugMenuStartWithoutDebugging {
            get {
                return ResourceManager.GetString("DebugMenuStartWithoutDebugging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;F5&apos; 的本地化字符串。
        /// </summary>
        public static string DebugMenuStartWithoutDebuggingCommandKey {
            get {
                return ResourceManager.GetString("DebugMenuStartWithoutDebuggingCommandKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Control 的本地化字符串。
        /// </summary>
        public static string DebugMenuStartWithoutDebuggingCommandModifier {
            get {
                return ResourceManager.GetString("DebugMenuStartWithoutDebuggingCommandModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string DialogCaptionError {
            get {
                return ResourceManager.GetString("DialogCaptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error Handling 的本地化字符串。
        /// </summary>
        public static string ErrorHandlingCategoryToToolbox {
            get {
                return ResourceManager.GetString("ErrorHandlingCategoryToToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error occurred loading document
        ///
        ///{0} 的本地化字符串。
        /// </summary>
        public static string ErrorLoadingDialogMessage {
            get {
                return ResourceManager.GetString("ErrorLoadingDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string ErrorLoadingDialogTitle {
            get {
                return ResourceManager.GetString("ErrorLoadingDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error occurred loading document
        ///
        ///{0} 的本地化字符串。
        /// </summary>
        public static string ErrorLoadingInDebugDialogMessage {
            get {
                return ResourceManager.GetString("ErrorLoadingInDebugDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string ErrorLoadingInDebugDialogTitle {
            get {
                return ResourceManager.GetString("ErrorLoadingInDebugDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error occurred running workflow
        ///
        ///{0} 的本地化字符串。
        /// </summary>
        public static string ErrorRunningDialogMessage {
            get {
                return ResourceManager.GetString("ErrorRunningDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string ErrorRunningDialogTitle {
            get {
                return ResourceManager.GetString("ErrorRunningDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string ErrorValidationItem {
            get {
                return ResourceManager.GetString("ErrorValidationItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workflow exception, see output window for stack trace 的本地化字符串。
        /// </summary>
        public static string ExceptionInDebugStatus {
            get {
                return ResourceManager.GetString("ExceptionInDebugStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workflow exception, see output window for stack trace 的本地化字符串。
        /// </summary>
        public static string ExceptionServiceHostStatus {
            get {
                return ResourceManager.GetString("ExceptionServiceHostStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workflow exception, see output window for stack trace 的本地化字符串。
        /// </summary>
        public static string ExceptionStatus {
            get {
                return ResourceManager.GetString("ExceptionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workflow exception, see output window for stack trace 的本地化字符串。
        /// </summary>
        public static string ExceptionWhenRunningInDebugStatus {
            get {
                return ResourceManager.GetString("ExceptionWhenRunningInDebugStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workflow service host faulted 的本地化字符串。
        /// </summary>
        public static string FaultedServiceHostInDebugStatus {
            get {
                return ResourceManager.GetString("FaultedServiceHostInDebugStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workflow service host faulted 的本地化字符串。
        /// </summary>
        public static string FaultedServiceHostStatus {
            get {
                return ResourceManager.GetString("FaultedServiceHostStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _File 的本地化字符串。
        /// </summary>
        public static string FileMenu {
            get {
                return ResourceManager.GetString("FileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Reference ... 的本地化字符串。
        /// </summary>
        public static string FileMenuAddReference {
            get {
                return ResourceManager.GetString("FileMenuAddReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string FileMenuClose {
            get {
                return ResourceManager.GetString("FileMenuClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close All 的本地化字符串。
        /// </summary>
        public static string FileMenuCloseAll {
            get {
                return ResourceManager.GetString("FileMenuCloseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string FileMenuExit {
            get {
                return ResourceManager.GetString("FileMenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Service ... 的本地化字符串。
        /// </summary>
        public static string FileMenuNewService {
            get {
                return ResourceManager.GetString("FileMenuNewService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Workflow ... 的本地化字符串。
        /// </summary>
        public static string FileMenuNewWorkflow {
            get {
                return ResourceManager.GetString("FileMenuNewWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open ... 的本地化字符串。
        /// </summary>
        public static string FileMenuOpen {
            get {
                return ResourceManager.GetString("FileMenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string FileMenuSave {
            get {
                return ResourceManager.GetString("FileMenuSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save All 的本地化字符串。
        /// </summary>
        public static string FileMenuSaveAll {
            get {
                return ResourceManager.GetString("FileMenuSaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save As ... 的本地化字符串。
        /// </summary>
        public static string FileMenuSaveAs {
            get {
                return ResourceManager.GetString("FileMenuSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flowchart 的本地化字符串。
        /// </summary>
        public static string FlowchartCategoryToToolbox {
            get {
                return ResourceManager.GetString("FlowchartCategoryToToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Help 的本地化字符串。
        /// </summary>
        public static string HelpMenu {
            get {
                return ResourceManager.GetString("HelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string HelpMenuAbout {
            get {
                return ResourceManager.GetString("HelpMenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Machine Learning Studio 的本地化字符串。
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Messaging 的本地化字符串。
        /// </summary>
        public static string MessagingCategoryToToolbox {
            get {
                return ResourceManager.GetString("MessagingCategoryToToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New workflow {0} 的本地化字符串。
        /// </summary>
        public static string NewWorkflowTabTitle {
            get {
                return ResourceManager.GetString("NewWorkflowTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New workflow {0} {1} 的本地化字符串。
        /// </summary>
        public static string NewWorkflowWithModifierTabTitle {
            get {
                return ResourceManager.GetString("NewWorkflowWithModifierTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workflow service host opened 的本地化字符串。
        /// </summary>
        public static string OpenServiceHostInDebugStatus {
            get {
                return ResourceManager.GetString("OpenServiceHostInDebugStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workflow service host opened 的本地化字符串。
        /// </summary>
        public static string OpenServiceHostStatus {
            get {
                return ResourceManager.GetString("OpenServiceHostStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Primitives 的本地化字符串。
        /// </summary>
        public static string PrimitivesCategoryToToolbox {
            get {
                return ResourceManager.GetString("PrimitivesCategoryToToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ready 的本地化字符串。
        /// </summary>
        public static string ReadyStatus {
            get {
                return ResourceManager.GetString("ReadyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workflow running ... 的本地化字符串。
        /// </summary>
        public static string RunningStatus {
            get {
                return ResourceManager.GetString("RunningStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Runtime 的本地化字符串。
        /// </summary>
        public static string RuntimeCategoryToToolbox {
            get {
                return ResourceManager.GetString("RuntimeCategoryToToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save changes to following workflows?
        ///{0} 的本地化字符串。
        /// </summary>
        public static string SaveChangesDialogMessage {
            get {
                return ResourceManager.GetString("SaveChangesDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Changes 的本地化字符串。
        /// </summary>
        public static string SaveChangesDialogTitle {
            get {
                return ResourceManager.GetString("SaveChangesDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save successful 的本地化字符串。
        /// </summary>
        public static string SaveSuccessfulStatus {
            get {
                return ResourceManager.GetString("SaveSuccessfulStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saving workflow ... 的本地化字符串。
        /// </summary>
        public static string SavingStatus {
            get {
                return ResourceManager.GetString("SavingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transaction 的本地化字符串。
        /// </summary>
        public static string TransactionCategoryToToolbox {
            get {
                return ResourceManager.GetString("TransactionCategoryToToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An unhandled exception occurred, see log for details : {0} 的本地化字符串。
        /// </summary>
        public static string UnhandledExceptionMessage {
            get {
                return ResourceManager.GetString("UnhandledExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unhandled exception occurred on {0} : {1} 的本地化字符串。
        /// </summary>
        public static string UnhandledExceptionTrace {
            get {
                return ResourceManager.GetString("UnhandledExceptionTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _View 的本地化字符串。
        /// </summary>
        public static string ViewMenu {
            get {
                return ResourceManager.GetString("ViewMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Debug 的本地化字符串。
        /// </summary>
        public static string ViewMenuDebug {
            get {
                return ResourceManager.GetString("ViewMenuDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Errors 的本地化字符串。
        /// </summary>
        public static string ViewMenuErrors {
            get {
                return ResourceManager.GetString("ViewMenuErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output 的本地化字符串。
        /// </summary>
        public static string ViewMenuOutput {
            get {
                return ResourceManager.GetString("ViewMenuOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Properties 的本地化字符串。
        /// </summary>
        public static string ViewMenuProperties {
            get {
                return ResourceManager.GetString("ViewMenuProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toolbox 的本地化字符串。
        /// </summary>
        public static string ViewMenuToolbox {
            get {
                return ResourceManager.GetString("ViewMenuToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        public static string WarningValidationItem {
            get {
                return ResourceManager.GetString("WarningValidationItem", resourceCulture);
            }
        }
    }
}
