//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Newtera.WFModel.Substitute {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SubstituteEntry {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SubstituteEntry() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Newtera.WFModel.Substitute.SubstituteEntry", typeof(SubstituteEntry).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Category 的本地化字符串。
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This category to which the attribute is classified. Using category for grouping attributes. 的本地化字符串。
        /// </summary>
        internal static string CategoryDescription {
            get {
                return ResourceManager.GetString("CategoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Effective Status 的本地化字符串。
        /// </summary>
        internal static string EffectiveStatus {
            get {
                return ResourceManager.GetString("EffectiveStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status of the substitute rule. If Disabled, the rule is not effecitive; If Immediately, the rule is effective; If Duration, the rule is effective during the specified duration 的本地化字符串。
        /// </summary>
        internal static string EffectiveStatusDescription {
            get {
                return ResourceManager.GetString("EffectiveStatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End Date 的本地化字符串。
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If effective status is Duration, this is the end date for rule being effective 的本地化字符串。
        /// </summary>
        internal static string EndDateDescription {
            get {
                return ResourceManager.GetString("EndDateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project Name 的本地化字符串。
        /// </summary>
        internal static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specify the name of a project within which the owner&apos;s tasks will be performed by the substitute. 的本地化字符串。
        /// </summary>
        internal static string ProjectNameDescription {
            get {
                return ResourceManager.GetString("ProjectNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Date 的本地化字符串。
        /// </summary>
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If effective status is Duration, this is the start date for rule being effective 的本地化字符串。
        /// </summary>
        internal static string StartDateDescription {
            get {
                return ResourceManager.GetString("StartDateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Substitute Users 的本地化字符串。
        /// </summary>
        internal static string SubstituteUsers {
            get {
                return ResourceManager.GetString("SubstituteUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specify users who are the substitutes for the owner&apos;s tasks. 的本地化字符串。
        /// </summary>
        internal static string SubstituteUsersDescription {
            get {
                return ResourceManager.GetString("SubstituteUsersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System 的本地化字符串。
        /// </summary>
        internal static string SystemCategory {
            get {
                return ResourceManager.GetString("SystemCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Task Scope 的本地化字符串。
        /// </summary>
        internal static string TaskScope {
            get {
                return ResourceManager.GetString("TaskScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specify the scope of owner&apos;s tasks to be performed by the substitute. If SpecificProject, a project name has to be specified. 的本地化字符串。
        /// </summary>
        internal static string TaskScopeDescription {
            get {
                return ResourceManager.GetString("TaskScopeDescription", resourceCulture);
            }
        }
    }
}
