create table CM_CHART_TEMP_INFO (
	ID VARCHAR(100)  not null,
	SCHEMANAME VARCHAR(50),
	VERSION VARCHAR(10),
	CLASSNAME VARCHAR(50)  not null,
	NAME VARCHAR(50) not null,
	TYPE VARCHAR(15) not null,
        DESCRIPTION VARCHAR(200),
	CREATETIME DATETIME default NOW(),
	XML LONGTEXT,
	CONSTRAINT CM_CHART_TEMP_INFO_PK PRIMARY KEY (ID)) ENGINE=InnoDB; 