create table CM_CLS_ATTACHMENT  (
   ID					VARCHAR(100)  not null ,
   CID					BIGINT     not null,
   SCHEMA_ID 			BIGINT,
   NAME                 VARCHAR(50)   not null,
   CLASSNAME            VARCHAR(30)   not null,
   TYPE                 VARCHAR(20)   not null,
   CREATETIME			DATETIME	default NOW(),
   ASIZE				BIGINT,
   IS_PUBLIC			TINYINT    not null,
   ATTACHMENT			LONGBLOB,
   CONSTRAINT PK_CM__CLS_ATTACHMENT PRIMARY KEY (ID),
   CONSTRAINT CM_CLS_ATTACHMENT_UN_ID UNIQUE(CID, NAME),
   CONSTRAINT FK_ATTACHEMNT_CLASS FOREIGN KEY(CID)
		REFERENCES MM_CLASS(ID) ON DELETE CASCADE   
   ) ENGINE=InnoDB;
