create table CM_PIVOT_LAYOUTS (
	ID VARCHAR(100)  not null,
	SCHEMANAME VARCHAR(50),
	VERSION VARCHAR(10),
	CLASSNAME VARCHAR(50)  not null,
	NAME VARCHAR(50) not null,
	VIEWNAME VARCHAR(50),
	DESCRIPTION VARCHAR(200),
        CREATETIME DATETIME default NOW(),
	XML LONGTEXT,
	CONSTRAINT CM_PIVOT_LAYOUTS_PK PRIMARY KEY (ID)) ENGINE=InnoDB;

-- SQLINES LICENSE FOR EVALUATION USE ONLY
create table WF_TASK_SUBSTITUTE (
	ID VARCHAR(10)  not null,
	XML LONGTEXT
	) ENGINE=InnoDB;

-- SQLINES LICENSE FOR EVALUATION USE ONLY
insert into WF_TASK_SUBSTITUTE(ID, XML) values('1', "");